// This file has been generated by Py++.

#include "Macros.h"
GCC_DIAG_OFF(unused-parameter);
GCC_DIAG_OFF(missing-field-initializers);
#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
GCC_DIAG_ON(unused-parameter);
GCC_DIAG_ON(missing-field-initializers);
#include "AttLimits.h"
#include "IChiSquaredModule.h"
#include "IMinimizer.h"
#include "ChiSquaredModule.h"
#include "FitSuite.h"
#include "FitSuiteParameters.h"
#include "MinimizerFactory.h"
#include "PythonPlusplusFitHelper.h"
#include "MathFunctions.h"
#include "ISquaredFunction.h"
#include "IOutputDataNormalizer.h"
#include "PythonInterface_enumerations.pypp.h"

namespace bp = boost::python;

void register_enumerations(){

    bp::enum_< MathFunctions::TransformCase>("TransformCase")
        .value("ForwardFFT", MathFunctions::ForwardFFT)
        .value("BackwardFFT", MathFunctions::BackwardFFT)
        .export_values()
        ;

}
