%import(module="libBornAgainParam") "Param/Base/ParameterPool.h"
%import(module="libBornAgainParam") "Param/Base/IModel.h"
%import(module="libBornAgainParam") "Param/Base/IParameterized.h"
%import(module="libBornAgainParam") "Param/Node/INode.h"
%import(module="libBornAgainParam") "Param/Distrib/ParameterDistribution.h"
