%import(module="libBornAgainParam") "Param/Base/ParameterPool.h"
%import(module="libBornAgainParam") "Param/Base/IComponent.h"
%import(module="libBornAgainParam") "Param/Base/IParametricComponent.h"
%import(module="libBornAgainParam") "Param/Node/INode.h"
%import(module="libBornAgainParam") "Param/Distrib/ParameterDistribution.h"
