# BornAgain Mac packaging 

if(BORNAGAIN_USE_PYTHON3)
  set(MAC_PYTHON_VERSION "python3")
else()
  set(MAC_PYTHON_VERSION "python2")
endif()

set(CPACK_PACKAGE_FILE_NAME
    "${CMAKE_PROJECT_NAME}-${BORNAGAIN_VERSION}-${MAC_PYTHON_VERSION}-${BORNAGAIN_ARCHITECTURE}-10.10+")

set(CPACK_BINARY_DRAGNDROP ON)
set(CPACK_GENERATOR "DragNDrop")


