// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence 
//! @brief automatically generated boost::python code for PythonCoreAPI  

#ifndef Beam_hpp__pyplusplus_wrapper
#define Beam_hpp__pyplusplus_wrapper

void register_Beam_class();

#endif//Beam_hpp__pyplusplus_wrapper
