// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence
//! @brief Automatically generated boost::python code for PythonCoreAPI

#ifndef DistributionGaussian_hpp__pyplusplus_wrapper
#define DistributionGaussian_hpp__pyplusplus_wrapper

void register_DistributionGaussian_class();

#endif//DistributionGaussian_hpp__pyplusplus_wrapper
