// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence 
//! @brief automatically generated boost::python code for PythonCoreAPI  

#ifndef DistributionCosine_hpp__pyplusplus_wrapper
#define DistributionCosine_hpp__pyplusplus_wrapper

void register_DistributionCosine_class();

#endif//DistributionCosine_hpp__pyplusplus_wrapper
