// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence
//! @brief Automatically generated boost::python code for PythonCoreAPI

#ifndef FTDistribution2DGate_hpp__pyplusplus_wrapper
#define FTDistribution2DGate_hpp__pyplusplus_wrapper

void register_FTDistribution2DGate_class();

#endif//FTDistribution2DGate_hpp__pyplusplus_wrapper
