// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence
//! @brief Automatically generated boost::python code for PythonCoreAPI

#ifndef IntensityData_hpp__pyplusplus_wrapper
#define IntensityData_hpp__pyplusplus_wrapper

void register_IntensityData_class();

#endif//IntensityData_hpp__pyplusplus_wrapper
