// This file has been generated by Py++.

#ifndef ISimulation_hpp__pyplusplus_wrapper
#define ISimulation_hpp__pyplusplus_wrapper

void register_ISimulation_class();

#endif//ISimulation_hpp__pyplusplus_wrapper
