// This file has been generated by Py++.

#ifndef MaterialManagerSingleton_t_hpp__pyplusplus_wrapper
#define MaterialManagerSingleton_t_hpp__pyplusplus_wrapper

void register_MaterialManagerSingleton_t_class();

#endif//MaterialManagerSingleton_t_hpp__pyplusplus_wrapper
