// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence 
//! @brief automatically generated boost::python code for PythonCoreAPI  

#ifndef ndimdata_t_hpp__pyplusplus_wrapper
#define ndimdata_t_hpp__pyplusplus_wrapper

void register_ndimdata_t_class();

#endif//ndimdata_t_hpp__pyplusplus_wrapper
