// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence 
//! @brief automatically generated boost::python code for PythonCoreAPI  

#ifndef ParticleDecoration_hpp__pyplusplus_wrapper
#define ParticleDecoration_hpp__pyplusplus_wrapper

void register_ParticleDecoration_class();

#endif//ParticleDecoration_hpp__pyplusplus_wrapper
