// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence 
//! @brief automatically generated boost::python code for PythonCoreAPI  

#ifndef Particle_hpp__pyplusplus_wrapper
#define Particle_hpp__pyplusplus_wrapper

void register_Particle_class();

#endif//Particle_hpp__pyplusplus_wrapper
