// This file has been generated by Py++.

#ifndef ReflectZ3D_hpp__pyplusplus_wrapper
#define ReflectZ3D_hpp__pyplusplus_wrapper

void register_ReflectZ3D_class();

#endif//ReflectZ3D_hpp__pyplusplus_wrapper
