// This file has been generated by Py++.

#ifndef ResolutionFunction2DSimple_hpp__pyplusplus_wrapper
#define ResolutionFunction2DSimple_hpp__pyplusplus_wrapper

void register_ResolutionFunction2DSimple_class();

#endif//ResolutionFunction2DSimple_hpp__pyplusplus_wrapper
