// This file has been generated by Py++.

#ifndef RotateZ3D_hpp__pyplusplus_wrapper
#define RotateZ3D_hpp__pyplusplus_wrapper

void register_RotateZ3D_class();

#endif//RotateZ3D_hpp__pyplusplus_wrapper
