// This file has been generated by Py++.

#ifndef RotateX3D_hpp__pyplusplus_wrapper
#define RotateX3D_hpp__pyplusplus_wrapper

void register_RotateX3D_class();

#endif//RotateX3D_hpp__pyplusplus_wrapper
