// This file has been generated by Py++.

#ifndef vdouble1d_t_hpp__pyplusplus_wrapper
#define vdouble1d_t_hpp__pyplusplus_wrapper

void register_vdouble1d_t_class();

#endif//vdouble1d_t_hpp__pyplusplus_wrapper
