// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence
//! @brief Automatically generated boost::python code for PythonFitAPI

#ifndef AttFitting_hpp__pyplusplus_wrapper
#define AttFitting_hpp__pyplusplus_wrapper

void register_AttFitting_class();

#endif//AttFitting_hpp__pyplusplus_wrapper
