// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence
//! @brief Automatically generated boost::python code for PythonFitAPI

#ifndef FitSuiteParameters_hpp__pyplusplus_wrapper
#define FitSuiteParameters_hpp__pyplusplus_wrapper

void register_FitSuiteParameters_class();

#endif//FitSuiteParameters_hpp__pyplusplus_wrapper
