// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence 
//! @brief automatically generated boost::python code for PythonCoreAPI  

#ifndef FitStrategyAdjustParameters_hpp__pyplusplus_wrapper
#define FitStrategyAdjustParameters_hpp__pyplusplus_wrapper

void register_FitStrategyAdjustParameters_class();

#endif//FitStrategyAdjustParameters_hpp__pyplusplus_wrapper
