// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence
//! @brief Automatically generated boost::python code for PythonFitAPI

#ifndef SquaredFunctionGaussianError_hpp__pyplusplus_wrapper
#define SquaredFunctionGaussianError_hpp__pyplusplus_wrapper

void register_SquaredFunctionGaussianError_class();

#endif//SquaredFunctionGaussianError_hpp__pyplusplus_wrapper
