# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "mavericks-dev"

# Use NFS for the shared folder
  config.vm.synced_folder '.', '/vagrant', disabled: true
  #config.vm.network "private_network", ip: "10.11.12.13"
  #config.vm.synced_folder ".", "/vagrant", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp,noatime']

  # Provider-specific configuration so you can fine-tune various
  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    #   vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpuidset", "1","000206a7","02100800","1fbae3bf","bfebfbff"]
    # use ICH9 for the chipset
    vb.customize ["modifyvm", :id, "--chipset", "piix3"]
    vb.cpus = 4
  end

  config.vm.provision :shell, path: "build_bornagain.sh", privileged: false

end
