# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "jhcook/osx-yosemite-10.10"

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.network "private_network", ip: "10.10.20.15"

config.vm.provider "virtualbox" do |vb|
  vb.customize ["modifyvm", :id, "--memory", "8192"]
  vb.customize ["modifyvm", :id, "--cpus", 2]
  vb.customize ["modifyvm", :id, "--audio", "none", "--usb", "on", "--usbehci", "off"]
end

config.vm.provision :shell, path: "build_bornagain.sh", privileged: false

end

