// This file has been generated by Py++.

// ************************************************************************** //
//
//  BornAgain: simulate and fit scattering at grazing incidence
//
//! @file      Automatically generated boost::python code for BornAgain Python bindings
//! @brief     Automatically generated boost::python code for BornAgain Python bindings
//!
//! @homepage  http://bornagainproject.org
//! @license   GNU General Public License v3 or higher (see COPYING)
//! @copyright Forschungszentrum Juelich GmbH 2015
//! @authors   Scientific Computing Group at MLZ Garching
//! @authors   C. Durniak, M. Ganeva, G. Pospelov, W. Van Herck, J. Wuttke
//
// ************************************************************************** //

#include "Macros.h"
GCC_DIAG_OFF(unused-parameter)
GCC_DIAG_OFF(missing-field-initializers)
#include "boost/python.hpp"
GCC_DIAG_ON(unused-parameter)
GCC_DIAG_ON(missing-field-initializers)
#include "__call_policies.pypp.hpp"
#include "__convenience.pypp.hpp"
#include "PythonCoreList.h"
#include "GISASSimulation.pypp.h"

namespace bp = boost::python;

struct GISASSimulation_wrapper : GISASSimulation, bp::wrapper< GISASSimulation > {

    GISASSimulation_wrapper( )
    : GISASSimulation( )
      , bp::wrapper< GISASSimulation >(){
        // null constructor
    m_pyobj = 0;
    }

    virtual ::GISASSimulation * clone(  ) const  {
        if( bp::override func_clone = this->get_override( "clone" ) )
            return func_clone(  );
        else{
            return this->GISASSimulation::clone(  );
        }
    }
    
    ::GISASSimulation * default_clone(  ) const  {
        return GISASSimulation::clone( );
    }

    virtual bool areParametersChanged(  ) {
        if( bp::override func_areParametersChanged = this->get_override( "areParametersChanged" ) )
            return func_areParametersChanged(  );
        else{
            return this->IParameterized::areParametersChanged(  );
        }
    }
    
    bool default_areParametersChanged(  ) {
        return IParameterized::areParametersChanged( );
    }

    virtual void clearParameterPool(  ) {
        if( bp::override func_clearParameterPool = this->get_override( "clearParameterPool" ) )
            func_clearParameterPool(  );
        else{
            this->IParameterized::clearParameterPool(  );
        }
    }
    
    void default_clearParameterPool(  ) {
        IParameterized::clearParameterPool( );
    }

    virtual ::ParameterPool * createParameterTree(  ) const  {
        if( bp::override func_createParameterTree = this->get_override( "createParameterTree" ) )
            return func_createParameterTree(  );
        else{
            return this->IParameterized::createParameterTree(  );
        }
    }
    
    ::ParameterPool * default_createParameterTree(  ) const  {
        return IParameterized::createParameterTree( );
    }

    virtual void printParameters(  ) const  {
        if( bp::override func_printParameters = this->get_override( "printParameters" ) )
            func_printParameters(  );
        else{
            this->IParameterized::printParameters(  );
        }
    }
    
    void default_printParameters(  ) const  {
        IParameterized::printParameters( );
    }

    virtual void registerParameter( ::std::string const & name, double * parpointer, ::AttLimits const & limits=AttLimits::limitless( ) ) {
        namespace bpl = boost::python;
        if( bpl::override func_registerParameter = this->get_override( "registerParameter" ) ){
            bpl::object py_result = bpl::call<bpl::object>( func_registerParameter.ptr(), name, parpointer, limits );
        }
        else{
            IParameterized::registerParameter( name, parpointer, boost::ref(limits) );
        }
    }
    
    static void default_registerParameter( ::IParameterized & inst, ::std::string const & name, long unsigned int parpointer, ::AttLimits const & limits=AttLimits::limitless( ) ){
        if( dynamic_cast< GISASSimulation_wrapper * >( boost::addressof( inst ) ) ){
            inst.::IParameterized::registerParameter(name, reinterpret_cast< double * >( parpointer ), limits);
        }
        else{
            inst.registerParameter(name, reinterpret_cast< double * >( parpointer ), limits);
        }
    }

    virtual bool setParameterValue( ::std::string const & name, double value ) {
        if( bp::override func_setParameterValue = this->get_override( "setParameterValue" ) )
            return func_setParameterValue( name, value );
        else{
            return this->IParameterized::setParameterValue( name, value );
        }
    }
    
    bool default_setParameterValue( ::std::string const & name, double value ) {
        return IParameterized::setParameterValue( name, value );
    }

    virtual void setParametersAreChanged(  ) {
        if( bp::override func_setParametersAreChanged = this->get_override( "setParametersAreChanged" ) )
            func_setParametersAreChanged(  );
        else{
            this->IParameterized::setParametersAreChanged(  );
        }
    }
    
    void default_setParametersAreChanged(  ) {
        IParameterized::setParametersAreChanged( );
    }

    virtual void transferToCPP(  ) {
        
        if( !this->m_pyobj) {
            this->m_pyobj = boost::python::detail::wrapper_base_::get_owner(*this);
            Py_INCREF(this->m_pyobj);
        }
        
        if( bp::override func_transferToCPP = this->get_override( "transferToCPP" ) )
            func_transferToCPP(  );
        else{
            this->ICloneable::transferToCPP(  );
        }
    }
    
    void default_transferToCPP(  ) {
        
        if( !this->m_pyobj) {
            this->m_pyobj = boost::python::detail::wrapper_base_::get_owner(*this);
            Py_INCREF(this->m_pyobj);
        }
        
        ICloneable::transferToCPP( );
    }

    PyObject* m_pyobj;

};

void register_GISASSimulation_class(){

    { //::GISASSimulation
        typedef bp::class_< GISASSimulation_wrapper, bp::bases< ICloneable, IParameterized >, std::auto_ptr< GISASSimulation_wrapper >, boost::noncopyable > GISASSimulation_exposer_t;
        GISASSimulation_exposer_t GISASSimulation_exposer = GISASSimulation_exposer_t( "GISASSimulation", "Main class to run the simulation.", bp::init< >() );
        bp::scope GISASSimulation_scope( GISASSimulation_exposer );
        { //::GISASSimulation::addParameterDistribution
        
            typedef void ( ::GISASSimulation::*addParameterDistribution_function_type)( ::std::string const &,::IDistribution1D const &,::std::size_t,double,::AttLimits const & ) ;
            
            GISASSimulation_exposer.def( 
                "addParameterDistribution"
                , addParameterDistribution_function_type( &::GISASSimulation::addParameterDistribution )
                , ( bp::arg("param_name"), bp::arg("distribution"), bp::arg("nbr_samples"), bp::arg("sigma_factor")=0.0, bp::arg("limits")=::AttLimits( ) ) );
        
        }
        { //::GISASSimulation::addParameterDistribution
        
            typedef void ( ::GISASSimulation::*addParameterDistribution_function_type)( ::ParameterDistribution const & ) ;
            
            GISASSimulation_exposer.def( 
                "addParameterDistribution"
                , addParameterDistribution_function_type( &::GISASSimulation::addParameterDistribution )
                , ( bp::arg("par_distr") )
                , "add a sampled parameter distribution." );
        
        }
        { //::GISASSimulation::clone
        
            typedef ::GISASSimulation * ( ::GISASSimulation::*clone_function_type)(  ) const;
            typedef ::GISASSimulation * ( GISASSimulation_wrapper::*default_clone_function_type)(  ) const;
            
            GISASSimulation_exposer.def( 
                "clone"
                , clone_function_type(&::GISASSimulation::clone)
                , default_clone_function_type(&GISASSimulation_wrapper::default_clone)
                , bp::return_value_policy< bp::manage_new_object >() );
        
        }
        { //::GISASSimulation::getDistributionHandler
        
            typedef ::DistributionHandler const & ( ::GISASSimulation::*getDistributionHandler_function_type)(  ) const;
            
            GISASSimulation_exposer.def( 
                "getDistributionHandler"
                , getDistributionHandler_function_type( &::GISASSimulation::getDistributionHandler )
                , bp::return_value_policy< bp::copy_const_reference >()
                , "add a sampled parameter distribution." );
        
        }
        { //::GISASSimulation::getInstrument
        
            typedef ::Instrument const & ( ::GISASSimulation::*getInstrument_function_type)(  ) const;
            
            GISASSimulation_exposer.def( 
                "getInstrument"
                , getInstrument_function_type( &::GISASSimulation::getInstrument )
                , bp::return_value_policy< bp::copy_const_reference >()
                , "Returns the instrument containing beam and detector information." );
        
        }
        { //::GISASSimulation::getIntensityData
        
            typedef ::OutputData< double > * ( ::GISASSimulation::*getIntensityData_function_type)(  ) const;
            
            GISASSimulation_exposer.def( 
                "getIntensityData"
                , getIntensityData_function_type( &::GISASSimulation::getIntensityData )
                , bp::return_value_policy< bp::manage_new_object >()
                , "Clone detector intensity map for all scan parameters (apply detector resolution function first)." );
        
        }
        { //::GISASSimulation::getSample
        
            typedef ::ISample * ( ::GISASSimulation::*getSample_function_type)(  ) const;
            
            GISASSimulation_exposer.def( 
                "getSample"
                , getSample_function_type( &::GISASSimulation::getSample )
                , bp::return_value_policy< bp::reference_existing_object >()
                , "Returns the sample." );
        
        }
        { //::GISASSimulation::getSampleBuilder
        
            typedef ::SampleBuilder_t ( ::GISASSimulation::*getSampleBuilder_function_type)(  ) const;
            
            GISASSimulation_exposer.def( 
                "getSampleBuilder"
                , getSampleBuilder_function_type( &::GISASSimulation::getSampleBuilder )
                , "return sample builder." );
        
        }
        { //::GISASSimulation::getSimulationParameters
        
            typedef ::SimulationParameters ( ::GISASSimulation::*getSimulationParameters_function_type)(  ) const;
            
            GISASSimulation_exposer.def( 
                "getSimulationParameters"
                , getSimulationParameters_function_type( &::GISASSimulation::getSimulationParameters )
                , "Sets detector parameters using parameter object." );
        
        }
        { //::GISASSimulation::normalize
        
            typedef void ( ::GISASSimulation::*normalize_function_type)(  ) ;
            
            GISASSimulation_exposer.def( 
                "normalize"
                , normalize_function_type( &::GISASSimulation::normalize )
                , "Normalize the detector counts." );
        
        }
        { //::GISASSimulation::prepareSimulation
        
            typedef void ( ::GISASSimulation::*prepareSimulation_function_type)(  ) ;
            
            GISASSimulation_exposer.def( 
                "prepareSimulation"
                , prepareSimulation_function_type( &::GISASSimulation::prepareSimulation )
                , "Put into a clean state for running a simulation." );
        
        }
        { //::GISASSimulation::removeDetectorResolutionFunction
        
            typedef void ( ::GISASSimulation::*removeDetectorResolutionFunction_function_type)(  ) ;
            
            GISASSimulation_exposer.def( 
                "removeDetectorResolutionFunction"
                , removeDetectorResolutionFunction_function_type( &::GISASSimulation::removeDetectorResolutionFunction )
                , "Removes detector resolution function." );
        
        }
        { //::GISASSimulation::runOMPISimulation
        
            typedef void ( ::GISASSimulation::*runOMPISimulation_function_type)(  ) ;
            
            GISASSimulation_exposer.def( 
                "runOMPISimulation"
                , runOMPISimulation_function_type( &::GISASSimulation::runOMPISimulation )
                , "Run an OpenMPI simulation." );
        
        }
        { //::GISASSimulation::runSimulation
        
            typedef void ( ::GISASSimulation::*runSimulation_function_type)(  ) ;
            
            GISASSimulation_exposer.def( 
                "runSimulation"
                , runSimulation_function_type( &::GISASSimulation::runSimulation )
                , "Run a simulation, possibly averaged over parameter distributions." );
        
        }
        { //::GISASSimulation::setAnalyzerProperties
        
            typedef void ( ::GISASSimulation::*setAnalyzerProperties_function_type)( ::kvector_t const &,double,double ) ;
            
            GISASSimulation_exposer.def( 
                "setAnalyzerProperties"
                , setAnalyzerProperties_function_type( &::GISASSimulation::setAnalyzerProperties )
                , ( bp::arg("direction"), bp::arg("efficiency"), bp::arg("total_transmission")=1.0e+0 )
                , "Sets the polarization analyzer characteristics of the detector." );
        
        }
        { //::GISASSimulation::setBeamIntensity
        
            typedef void ( ::GISASSimulation::*setBeamIntensity_function_type)( double ) ;
            
            GISASSimulation_exposer.def( 
                "setBeamIntensity"
                , setBeamIntensity_function_type( &::GISASSimulation::setBeamIntensity )
                , ( bp::arg("intensity") )
                , "Sets beam intensity from here (forwarded to Instrument)." );
        
        }
        { //::GISASSimulation::setBeamParameters
        
            typedef void ( ::GISASSimulation::*setBeamParameters_function_type)( double,double,double ) ;
            
            GISASSimulation_exposer.def( 
                "setBeamParameters"
                , setBeamParameters_function_type( &::GISASSimulation::setBeamParameters )
                , ( bp::arg("wavelength"), bp::arg("alpha_i"), bp::arg("phi_i") )
                , "Sets beam parameters from here (forwarded to Instrument)." );
        
        }
        { //::GISASSimulation::setBeamPolarization
        
            typedef void ( ::GISASSimulation::*setBeamPolarization_function_type)( ::kvector_t const & ) ;
            
            GISASSimulation_exposer.def( 
                "setBeamPolarization"
                , setBeamPolarization_function_type( &::GISASSimulation::setBeamPolarization )
                , ( bp::arg("bloch_vector") )
                , "Sets the beam polarization according to the given Bloch vector." );
        
        }
        { //::GISASSimulation::setDetectorParameters
        
            typedef void ( ::GISASSimulation::*setDetectorParameters_function_type)( ::OutputData< double > const & ) ;
            
            GISASSimulation_exposer.def( 
                "setDetectorParameters"
                , setDetectorParameters_function_type( &::GISASSimulation::setDetectorParameters )
                , ( bp::arg("output_data") )
                , "Sets detector parameters using axes of output data." );
        
        }
        { //::GISASSimulation::setDetectorParameters
        
            typedef void ( ::GISASSimulation::*setDetectorParameters_function_type)( ::std::size_t,double,double,::std::size_t,double,double,bool ) ;
            
            GISASSimulation_exposer.def( 
                "setDetectorParameters"
                , setDetectorParameters_function_type( &::GISASSimulation::setDetectorParameters )
                , ( bp::arg("n_phi"), bp::arg("phi_f_min"), bp::arg("phi_f_max"), bp::arg("n_alpha"), bp::arg("alpha_f_min"), bp::arg("alpha_f_max"), bp::arg("isgisaxs_style")=(bool)(false) )
                , "Sets detector parameters using angle ranges." );
        
        }
        { //::GISASSimulation::setDetectorParameters
        
            typedef void ( ::GISASSimulation::*setDetectorParameters_function_type)( ::DetectorParameters const & ) ;
            
            GISASSimulation_exposer.def( 
                "setDetectorParameters"
                , setDetectorParameters_function_type( &::GISASSimulation::setDetectorParameters )
                , ( bp::arg("params") )
                , "Sets detector parameters using parameter object." );
        
        }
        { //::GISASSimulation::setDetectorResolutionFunction
        
            typedef void ( ::GISASSimulation::*setDetectorResolutionFunction_function_type)( ::IResolutionFunction2D const & ) ;
            
            GISASSimulation_exposer.def( 
                "setDetectorResolutionFunction"
                , setDetectorResolutionFunction_function_type( &::GISASSimulation::setDetectorResolutionFunction )
                , ( bp::arg("resolution_function") )
                , "Define resolution function for detector." );
        
        }
        { //::GISASSimulation::setInstrument
        
            typedef void ( ::GISASSimulation::*setInstrument_function_type)( ::Instrument const & ) ;
            
            GISASSimulation_exposer.def( 
                "setInstrument"
                , setInstrument_function_type( &::GISASSimulation::setInstrument )
                , ( bp::arg("instrument") )
                , "Sets the instrument containing beam and detector information." );
        
        }
        { //::GISASSimulation::setSample
        
            typedef void ( ::GISASSimulation::*setSample_function_type)( ::ISample const & ) ;
            
            GISASSimulation_exposer.def( 
                "setSample"
                , setSample_function_type( &::GISASSimulation::setSample )
                , ( bp::arg("sample") )
                , "Sets the sample to be tested." );
        
        }
        { //::GISASSimulation::setSampleBuilder
        
            typedef void ( ::GISASSimulation::*setSampleBuilder_function_type)( ::SampleBuilder_t ) ;
            
            GISASSimulation_exposer.def( 
                "setSampleBuilder"
                , setSampleBuilder_function_type( &::GISASSimulation::setSampleBuilder )
                , ( bp::arg("sample_builder") )
                , "Sets the sample builder." );
        
        }
        { //::GISASSimulation::setSimulationParameters
        
            typedef void ( ::GISASSimulation::*setSimulationParameters_function_type)( ::SimulationParameters const & ) ;
            
            GISASSimulation_exposer.def( 
                "setSimulationParameters"
                , setSimulationParameters_function_type( &::GISASSimulation::setSimulationParameters )
                , ( bp::arg("sim_params") )
                , "Sets simulation parameters." );
        
        }
        { //::GISASSimulation::setThreadInfo
        
            typedef void ( ::GISASSimulation::*setThreadInfo_function_type)( ::ThreadInfo const & ) ;
            
            GISASSimulation_exposer.def( 
                "setThreadInfo"
                , setThreadInfo_function_type( &::GISASSimulation::setThreadInfo )
                , ( bp::arg("thread_info") )
                , "Sets the batch and thread information to be used." );
        
        }
        { //::IParameterized::areParametersChanged
        
            typedef bool ( ::IParameterized::*areParametersChanged_function_type)(  ) ;
            typedef bool ( GISASSimulation_wrapper::*default_areParametersChanged_function_type)(  ) ;
            
            GISASSimulation_exposer.def( 
                "areParametersChanged"
                , areParametersChanged_function_type(&::IParameterized::areParametersChanged)
                , default_areParametersChanged_function_type(&GISASSimulation_wrapper::default_areParametersChanged) );
        
        }
        { //::IParameterized::clearParameterPool
        
            typedef void ( ::IParameterized::*clearParameterPool_function_type)(  ) ;
            typedef void ( GISASSimulation_wrapper::*default_clearParameterPool_function_type)(  ) ;
            
            GISASSimulation_exposer.def( 
                "clearParameterPool"
                , clearParameterPool_function_type(&::IParameterized::clearParameterPool)
                , default_clearParameterPool_function_type(&GISASSimulation_wrapper::default_clearParameterPool) );
        
        }
        { //::IParameterized::createParameterTree
        
            typedef ::ParameterPool * ( ::IParameterized::*createParameterTree_function_type)(  ) const;
            typedef ::ParameterPool * ( GISASSimulation_wrapper::*default_createParameterTree_function_type)(  ) const;
            
            GISASSimulation_exposer.def( 
                "createParameterTree"
                , createParameterTree_function_type(&::IParameterized::createParameterTree)
                , default_createParameterTree_function_type(&GISASSimulation_wrapper::default_createParameterTree)
                , bp::return_value_policy< bp::manage_new_object >() );
        
        }
        { //::IParameterized::printParameters
        
            typedef void ( ::IParameterized::*printParameters_function_type)(  ) const;
            typedef void ( GISASSimulation_wrapper::*default_printParameters_function_type)(  ) const;
            
            GISASSimulation_exposer.def( 
                "printParameters"
                , printParameters_function_type(&::IParameterized::printParameters)
                , default_printParameters_function_type(&GISASSimulation_wrapper::default_printParameters) );
        
        }
        { //::IParameterized::registerParameter
        
            typedef void ( *default_registerParameter_function_type )( ::IParameterized &,::std::string const &,long unsigned int,::AttLimits const & );
            
            GISASSimulation_exposer.def( 
                "registerParameter"
                , default_registerParameter_function_type( &GISASSimulation_wrapper::default_registerParameter )
                , ( bp::arg("inst"), bp::arg("name"), bp::arg("parpointer"), bp::arg("limits")=AttLimits::limitless( ) )
                , "main method to register data address in the pool." );
        
        }
        { //::IParameterized::setParameterValue
        
            typedef bool ( ::IParameterized::*setParameterValue_function_type)( ::std::string const &,double ) ;
            typedef bool ( GISASSimulation_wrapper::*default_setParameterValue_function_type)( ::std::string const &,double ) ;
            
            GISASSimulation_exposer.def( 
                "setParameterValue"
                , setParameterValue_function_type(&::IParameterized::setParameterValue)
                , default_setParameterValue_function_type(&GISASSimulation_wrapper::default_setParameterValue)
                , ( bp::arg("name"), bp::arg("value") ) );
        
        }
        { //::IParameterized::setParametersAreChanged
        
            typedef void ( ::IParameterized::*setParametersAreChanged_function_type)(  ) ;
            typedef void ( GISASSimulation_wrapper::*default_setParametersAreChanged_function_type)(  ) ;
            
            GISASSimulation_exposer.def( 
                "setParametersAreChanged"
                , setParametersAreChanged_function_type(&::IParameterized::setParametersAreChanged)
                , default_setParametersAreChanged_function_type(&GISASSimulation_wrapper::default_setParametersAreChanged) );
        
        }
        { //::ICloneable::transferToCPP
        
            typedef void ( ::ICloneable::*transferToCPP_function_type)(  ) ;
            typedef void ( GISASSimulation_wrapper::*default_transferToCPP_function_type)(  ) ;
            
            GISASSimulation_exposer.def( 
                "transferToCPP"
                , transferToCPP_function_type(&::ICloneable::transferToCPP)
                , default_transferToCPP_function_type(&GISASSimulation_wrapper::default_transferToCPP) );
        
        }
    }

}
