// This file has been generated by Py++.

// BornAgain: simulate and fit scattering at grazing incidence 
//! @brief automatically generated boost::python code for PythonCoreAPI  

#include "Macros.h"
GCC_DIAG_OFF(unused-parameter);
GCC_DIAG_OFF(missing-field-initializers);
#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
GCC_DIAG_ON(unused-parameter);
GCC_DIAG_ON(missing-field-initializers);
#include "PythonCoreList.h"
#include "vector_less__ParameterSample__greater_.pypp.h"

namespace bp = boost::python;

void register_vector_less__ParameterSample__greater__class(){

    { //scope begin
        typedef bp::class_< std::vector< ParameterSample > > vector_less__ParameterSample__greater__exposer_t;
        vector_less__ParameterSample__greater__exposer_t vector_less__ParameterSample__greater__exposer = vector_less__ParameterSample__greater__exposer_t("vector_less__ParameterSample__greater_");
        bp::scope vector_less__ParameterSample__greater__scope( vector_less__ParameterSample__greater__exposer );
        //WARNING: the next line of code will not compile, because "::ParameterSample" does not have operator== !
        vector_less__ParameterSample__greater__exposer.def( bp::vector_indexing_suite< ::std::vector< ParameterSample > >() );
    } //scope end

}
